@URL = http://localhost:3000

GET {{URL}}/Tasks
###
GET {{URL}}/Tasks/60fc8c8f77ccf62c08c1113d
###
POST {{URL}}/Tasks
Content-Type: application/json

{
    "title": "My first Task",
    "description": "This is my first Task"
}

###
PUT {{URL}}/Tasks/60fc8c8f77ccf62c08c1113d
Content-Type: application/json

{
    "title": "My first Task",
    "description": "This is my Task Updated"
}
###
DELETE {{URL}}/Tasks/60fc69c181c4c2123028cc04