@URL = http://localhost:3000

GET {{URL}}/Tasks
###
GET {{URL}}/Tasks/60fc8c8f77ccf62c08c1113d
###
POST {{URL}}/Tasks
Content-Type: application/json

{
    "title": "Test task",
    "description": "This is a new Task",
    "deadline": "25/08/2021"
}

###
PUT {{URL}}/Tasks/60fc8c8f77ccf62c08c1113d
Content-Type: application/json

{
    "title": "My first Task",
    "description": "This is my Task Updated"
}
###
DELETE {{URL}}/Tasks/60fef337bc10602388835ff0

###
GET {{URL}}/Users
###
GET {{URL}}/USers/6106aa8fa50f8510e8dfd5ae
###
POST {{URL}}/Users
Content-Type: application/json

{
    "userName": "amb",
    "password": "123"
}

###
PUT {{URL}}/Users/6106aa8fa50f8510e8dfd5ae
Content-Type: application/json

{
    "userName": "amb",
    "password": "125"
}


###
DELETE {{URL}}/Tasks/60fef337bc10602388835ff0